import { useState } from "react";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card } from "@/components/ui/card";
import { Loader2, Plus, Download, Trash2 } from "lucide-react";
import { Link } from "wouter";
import { toast } from "sonner";
import AnalysisResults from "@/components/AnalysisResults";
import AnalysisHistory from "@/components/AnalysisHistory";

export default function Dashboard() {
  const { user } = useAuth();
  const [repositoryUrl, setRepositoryUrl] = useState("");
  const [activeAnalysisId, setActiveAnalysisId] = useState<number | null>(null);
  const [showHistory, setShowHistory] = useState(false);

  const initiateAnalysisMutation = trpc.analysis.initiate.useMutation();
  const historyQuery = trpc.analysis.history.useQuery();
  const resultsQuery = trpc.analysis.getResults.useQuery(
    { analysisId: activeAnalysisId! },
    { enabled: activeAnalysisId !== null }
  );
  const deleteAnalysisMutation = trpc.analysis.delete.useMutation();

  const handleAnalyze = async () => {
    if (!repositoryUrl.trim()) {
      toast.error("Please enter a repository URL");
      return;
    }

    try {
      const result = await initiateAnalysisMutation.mutateAsync({
        repositoryUrl,
      });
      setActiveAnalysisId(result.analysisId);
      setRepositoryUrl("");
      toast.success("Analysis started! Processing your repository...");
      historyQuery.refetch();
    } catch (error) {
      toast.error(
        error instanceof Error ? error.message : "Failed to start analysis"
      );
    }
  };

  const handleDelete = async (analysisId: number) => {
    if (!confirm("Are you sure you want to delete this analysis?")) return;

    try {
      await deleteAnalysisMutation.mutateAsync({ analysisId });
      toast.success("Analysis deleted");
      if (activeAnalysisId === analysisId) {
        setActiveAnalysisId(null);
      }
      historyQuery.refetch();
    } catch (error) {
      toast.error("Failed to delete analysis");
    }
  };

  const handleExport = async () => {
    if (!activeAnalysisId || !resultsQuery.data) return;

    try {
      const analysis = resultsQuery.data.analysis;
      const results = resultsQuery.data.results;

      const tags = results?.suggestedTags
        ? JSON.parse(results.suggestedTags)
        : [];
      const categories = results?.suggestedCategories
        ? JSON.parse(results.suggestedCategories)
        : [];
      const missingSections = results?.missingSections
        ? JSON.parse(results.missingSections)
        : [];
      const visualEnhancements = results?.visualEnhancements
        ? JSON.parse(results.visualEnhancements)
        : [];

      const markdown = `# Repository Analysis Report

## Repository Information
- **Name**: ${analysis.repositoryName}
- **Owner**: ${analysis.repositoryOwner}
- **URL**: ${analysis.repositoryUrl}
- **Analysis Date**: ${new Date(analysis.createdAt).toLocaleDateString()}

## Overall Score
**${results?.overallScore || 0}/100**

## Title Suggestion
${results?.titleSuggestion || "No suggestion"}

## Summary Improvement
${results?.summaryImprovement || "No suggestion"}

## Suggested Tags
${tags.map((tag: string) => `- ${tag}`).join("\n") || "No tags suggested"}

## Suggested Categories
${categories.map((cat: string) => `- ${cat}`).join("\n") || "No categories suggested"}

## Missing Sections
${missingSections.map((section: string) => `- ${section}`).join("\n") || "No missing sections identified"}

## Visual Enhancements
${visualEnhancements.map((enhancement: string) => `- ${enhancement}`).join("\n") || "No enhancements suggested"}

---
*Generated by AAIDC Multi-Agent Publication Assistant*`;

      const element = document.createElement("a");
      const file = new Blob([markdown], { type: "text/markdown" });
      element.href = URL.createObjectURL(file);
      element.download = `analysis-${activeAnalysisId}.md`;
      document.body.appendChild(element);
      element.click();
      document.body.removeChild(element);

      toast.success("Analysis exported as markdown");
    } catch (error) {
      toast.error("Failed to export analysis");
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900">
      {/* Navigation */}
      <nav className="border-b border-slate-700/50 backdrop-blur-sm sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4 flex justify-between items-center">
          <Link href="/">
            <span className="text-xl font-bold text-white cursor-pointer">
              RepoAssistant
            </span>
          </Link>
          <div className="text-sm text-slate-400">
            Welcome, {user?.name || "User"}
          </div>
        </div>
      </nav>

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* Input Section */}
        <Card className="bg-slate-800/50 border-slate-700/50 p-6 mb-8">
          <h2 className="text-2xl font-bold text-white mb-4">
            Analyze a Repository
          </h2>
          <div className="flex gap-2">
            <Input
              placeholder="Enter GitHub repository URL (e.g., https://github.com/owner/repo)"
              value={repositoryUrl}
              onChange={(e) => setRepositoryUrl(e.target.value)}
              onKeyPress={(e) => e.key === "Enter" && handleAnalyze()}
              className="bg-slate-700/50 border-slate-600 text-white placeholder:text-slate-500"
              disabled={initiateAnalysisMutation.isPending}
            />
            <Button
              onClick={handleAnalyze}
              disabled={initiateAnalysisMutation.isPending}
              className="bg-blue-600 hover:bg-blue-700"
            >
              {initiateAnalysisMutation.isPending ? (
                <>
                  <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                  Analyzing...
                </>
              ) : (
                <>
                  <Plus className="w-4 h-4 mr-2" />
                  Analyze
                </>
              )}
            </Button>
          </div>
        </Card>

        {/* Main Content */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          {/* Results Section */}
          <div className="lg:col-span-2">
            {activeAnalysisId && resultsQuery.data ? (
              <div className="space-y-4">
                <div className="flex justify-between items-center">
                  <h3 className="text-xl font-bold text-white">
                    Analysis Results
                  </h3>
                  <div className="flex gap-2">
                    <Button
                      size="sm"
                      variant="outline"
                      onClick={handleExport}
                      className="border-slate-600"
                    >
                      <Download className="w-4 h-4 mr-2" />
                      Export
                    </Button>
                    <Button
                      size="sm"
                      variant="outline"
                      onClick={() => handleDelete(activeAnalysisId)}
                      className="border-red-600/50 text-red-400 hover:bg-red-600/10"
                    >
                      <Trash2 className="w-4 h-4 mr-2" />
                      Delete
                    </Button>
                  </div>
                </div>
                <AnalysisResults data={resultsQuery.data} />
              </div>
            ) : activeAnalysisId && resultsQuery.isPending ? (
              <Card className="bg-slate-800/50 border-slate-700/50 p-12 text-center">
                <Loader2 className="w-12 h-12 animate-spin text-blue-400 mx-auto mb-4" />
                <p className="text-slate-300">
                  Processing your repository with our multi-agent system...
                </p>
              </Card>
            ) : (
              <Card className="bg-slate-800/50 border-slate-700/50 p-12 text-center">
                <p className="text-slate-400">
                  Select an analysis from the history or analyze a new repository
                </p>
              </Card>
            )}
          </div>

          {/* History Section */}
          <div>
            <div className="flex justify-between items-center mb-4">
              <h3 className="text-xl font-bold text-white">Analysis History</h3>
              <Button
                size="sm"
                variant="ghost"
                onClick={() => setShowHistory(!showHistory)}
                className="text-blue-400"
              >
                {showHistory ? "Hide" : "Show"}
              </Button>
            </div>

            {showHistory && (
              <AnalysisHistory
                analyses={historyQuery.data || []}
                activeId={activeAnalysisId}
                onSelect={setActiveAnalysisId}
                onDelete={handleDelete}
              />
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
